server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jhonYaFei/Spring-Cloud-Demo-Config.git
          clone-on-start: true
  application:
    name: microservice-config-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://yy:yy@localhost:8761/eureka
  instance:
    prefer-ip-address: true