spring:
  application:
    name: microservice-consumer-movie
server:
  port: 7901
  ##context-path: /movie
user: 
  userServicePath: http://localhost:7900/user/simple/
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true