spring:
  application:
    name: microservice-gateway-zuul
server:
  port: 8040
eureka:
  client:
    service-url:
      defaultZone: http://yy:yy@localhost:8761/eureka
  instance:
    prefer-ip-address: true
zuul:
  strip-prefix: false
  prefix: /api